services:
  - type: web
    name: backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: static_site
    name: frontend
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
  - type: static_site
    name: dashboard
    rootDir: dashboard
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
