services:
  - type: web
    name: backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
  - type: web
    name: frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
  - type: web
    name: dashboard
    env: static
    rootDir: dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: dist
